import type { TradeTrack } from "../resume-builder/trade-content";

export type TradeCareerFamily = {
  slug: string;
  name: string;
  description: string;
  resumeFocus: string;
  roles: readonly string[];
  builderTrack: TradeTrack;
  guideHref?: string;
};

/**
 * The public TRADE HUSTL3 career map.
 *
 * A role listed here counts as one mapped job title. It does not count as a
 * resume template or a dedicated SEO page. `guideHref` is present only when a
 * live, trade-specific guided builder page already exists.
 */
export const TRADE_CAREER_FAMILIES: readonly TradeCareerFamily[] = [
  {
    slug: "hvac-refrigeration",
    name: "HVAC & Refrigeration",
    description: "Residential, commercial, industrial, and cold-side service, installation, controls, and maintenance work.",
    resumeFocus: "Systems serviced, diagnostic tools, refrigerant credentials, PM scope, call volume, and measurable equipment results.",
    builderTrack: "HVAC & Refrigeration",
    guideHref: "/resume-builder/hvac",
    roles: [
      "HVAC Service Technician",
      "HVAC Installer",
      "Commercial HVAC Technician",
      "Residential HVAC Technician",
      "Refrigeration Technician",
      "Rack Refrigeration Technician",
      "Chiller Technician",
      "Boiler Technician",
      "Building Automation Technician",
      "HVAC Controls Technician",
      "Duct Installer",
      "Sheet Metal HVAC Installer",
    ],
  },
  {
    slug: "electrical-low-voltage",
    name: "Electrical & Low Voltage",
    description: "Power, lighting, controls, communications, life-safety, renewable-energy, and specialty electrical work.",
    resumeFocus: "License level, apprenticeship hours, voltage and systems, conduit and termination scope, testing tools, and code-compliant results.",
    builderTrack: "Electrical",
    guideHref: "/resume-builder/electrician",
    roles: [
      "Electrician",
      "Apprentice Electrician",
      "Commercial Electrician",
      "Industrial Electrician",
      "Residential Electrician",
      "Electrical Maintenance Technician",
      "Low Voltage Technician",
      "Fire Alarm Technician",
      "Security Systems Installer",
      "Data Cabling Technician",
      "Solar PV Installer",
      "EV Charger Installer",
      "Traffic Signal Technician",
    ],
  },
  {
    slug: "plumbing-pipefitting",
    name: "Plumbing & Pipefitting",
    description: "Service, new construction, industrial piping, fire protection, drain work, water systems, and specialty fitting.",
    resumeFocus: "License level, materials joined, systems installed, fixtures or footage completed, service-call volume, tests, and callbacks reduced.",
    builderTrack: "Plumbing",
    guideHref: "/resume-builder/plumbing",
    roles: [
      "Plumber",
      "Apprentice Plumber",
      "Service Plumber",
      "Commercial Plumber",
      "Residential Plumber",
      "Pipefitter",
      "Steamfitter",
      "Sprinkler Fitter",
      "Backflow Technician",
      "Drain Technician",
      "Sewer Camera Technician",
      "Water Treatment Technician",
      "Gas Fitter",
    ],
  },
  {
    slug: "construction-carpentry",
    name: "Construction & Carpentry",
    description: "Ground-up construction, renovation, structural and finish carpentry, interior systems, concrete, and project closeout.",
    resumeFocus: "Project type, square footage, materials, prints and layout, installed quantities, crew scope, safety, and schedule performance.",
    builderTrack: "Construction & Carpentry",
    guideHref: "/resume-builder/construction-carpentry",
    roles: [
      "Carpenter",
      "Apprentice Carpenter",
      "Framing Carpenter",
      "Finish Carpenter",
      "Form Carpenter",
      "Cabinet Installer",
      "Millwork Installer",
      "Drywall Installer",
      "Drywall Finisher",
      "Flooring Installer",
      "Tile Setter",
      "Glazier",
      "Construction Superintendent",
      "Construction Punch Technician",
      "Remodeling Technician",
    ],
  },
  {
    slug: "facilities-property-apartment-maintenance",
    name: "Facilities, Property & Apartment Maintenance",
    description: "Multi-trade building care across apartments, commercial sites, schools, hospitals, hotels, and public facilities.",
    resumeFocus: "Buildings or units covered, work-order volume, PM completion, systems supported, response time, vendor coordination, and uptime.",
    builderTrack: "Facilities Maintenance",
    guideHref: "/resume-builder/facilities-maintenance",
    roles: [
      "Facilities Maintenance Technician",
      "Building Engineer",
      "Apartment Maintenance Technician",
      "Make-Ready Technician",
      "Maintenance Supervisor",
      "Property Maintenance Technician",
      "Hotel Maintenance Engineer",
      "School Maintenance Technician",
      "Hospital Facilities Technician",
      "Mobile Maintenance Technician",
      "Custodial Maintenance Technician",
      "Commercial Building Technician",
      "Housing Authority Maintenance Technician",
      "Campus Facilities Technician",
    ],
  },
  {
    slug: "welding-fabrication-machining",
    name: "Welding, Fabrication & Machining",
    description: "Structural, pipe, production, repair, precision machining, fit-up, and metal-forming work.",
    resumeFocus: "Processes and positions, materials and thicknesses, drawing tolerances, production volume, inspection results, and current qualifications.",
    builderTrack: "Welding & Fabrication",
    guideHref: "/resume-builder/welding-fabrication",
    roles: [
      "Welder",
      "MIG Welder",
      "TIG Welder",
      "Stick Welder",
      "Pipe Welder",
      "Structural Welder",
      "Production Welder",
      "Welder Fabricator",
      "Fitter Welder",
      "Sheet Metal Fabricator",
      "CNC Machinist",
      "Manual Machinist",
      "CNC Operator",
      "Metal Fabrication Technician",
      "Welding Inspector",
    ],
  },
  {
    slug: "general-labor-trade-helpers",
    name: "General Labor & Trade Helpers",
    description: "Jobsite, shop, plant, and property support that keeps crews supplied, safe, clean, and moving.",
    resumeFocus: "Trade supported, tools and equipment used, loads or sites handled, attendance, safety training, pace, and crew contribution.",
    builderTrack: "General Labor / Trade Helper",
    guideHref: "/resume-builder/general-labor",
    roles: [
      "General Laborer",
      "Construction Helper",
      "Electrician Helper",
      "Plumber Helper",
      "HVAC Helper",
      "Welder Helper",
      "Maintenance Helper",
      "Demolition Laborer",
      "Site Cleanup Laborer",
      "Utility Laborer",
      "Shop Helper",
      "Trade Apprentice",
    ],
  },
  {
    slug: "commercial-driving-transportation",
    name: "Commercial Driving & Transportation",
    description: "Freight, passenger, specialty, local-route, public-service, and private transportation careers—not just Class A trucking.",
    resumeFocus: "License class and endorsements, equipment, route type, mileage, passengers or stops, inspection record, safety, and on-time performance.",
    builderTrack: "Commercial Driving & Transportation",
    roles: [
      "Class A CDL Driver",
      "Class B CDL Driver",
      "Over-the-Road Truck Driver",
      "Regional Truck Driver",
      "Local Truck Driver",
      "Dedicated Route Driver",
      "Flatbed Truck Driver",
      "Tanker Driver",
      "Hazmat Driver",
      "Dump Truck Driver",
      "Ready-Mix Concrete Driver",
      "Refuse and Recycling Driver",
      "Tow Truck Driver",
      "School Bus Driver",
      "Public Transit Bus Driver",
      "Charter Bus Driver",
      "Motor Coach Driver",
      "Shuttle Driver",
      "Paratransit Driver",
      "Chauffeur",
      "Black Car Driver",
      "Limousine Driver",
      "Box Truck Driver",
      "Local Delivery Driver",
      "Route Delivery Driver",
      "Medical Transport Driver",
      "Non-Emergency Medical Transportation Driver",
    ],
  },
  {
    slug: "warehouse-logistics-material-handling",
    name: "Warehouse, Logistics & Material Handling",
    description: "Receiving, storage, picking, inventory, dock, distribution, fulfillment, and material-movement work.",
    resumeFocus: "Units, orders, pallets, accuracy, equipment authorizations, warehouse systems, dock or zone scope, productivity, and safety.",
    builderTrack: "Warehouse, Logistics & Material Handling",
    roles: [
      "Warehouse Associate",
      "Forklift Operator",
      "Shipping and Receiving Clerk",
      "Order Picker",
      "Inventory Specialist",
      "Dock Worker",
      "Loader and Unloader",
      "Material Handler",
      "Distribution Center Associate",
      "Fulfillment Associate",
      "Warehouse Lead",
      "Warehouse Supervisor",
      "Yard Jockey",
      "Crane and Hoist Operator",
      "Rigging Technician",
    ],
  },
  {
    slug: "industrial-warehouse-maintenance",
    name: "Industrial & Warehouse Maintenance",
    description: "Production, distribution, conveyor, packaging, controls, reliability, and plant-equipment maintenance.",
    resumeFocus: "Assets supported, PM and downtime results, electrical and mechanical systems, controls, parts, CMMS use, and root-cause repairs.",
    builderTrack: "Industrial & Warehouse Maintenance",
    roles: [
      "Industrial Maintenance Technician",
      "Maintenance Mechanic",
      "Electro-Mechanical Technician",
      "Conveyor Maintenance Technician",
      "Automation Technician",
      "Controls Technician",
      "PLC Technician",
      "Reliability Technician",
      "Packaging Machine Technician",
      "Ammonia Refrigeration Technician",
      "Millwright",
      "Maintenance Planner",
      "Plant Maintenance Technician",
      "Manufacturing Maintenance Technician",
      "Robotics Technician",
    ],
  },
  {
    slug: "landscaping-grounds-maintenance",
    name: "Landscaping & Grounds Maintenance",
    description: "Commercial and residential landscape care, irrigation, turf, tree work, grounds, and seasonal services.",
    resumeFocus: "Acres or properties covered, routes, equipment, applications, irrigation zones, crew size, seasonal work, and quality or safety results.",
    builderTrack: "Landscaping & Grounds Maintenance",
    roles: [
      "Landscaper",
      "Groundskeeper",
      "Lawn Care Technician",
      "Irrigation Technician",
      "Tree Care Technician",
      "Arborist",
      "Landscape Crew Leader",
      "Commercial Mower Operator",
      "Pesticide Applicator",
      "Snow Removal Operator",
      "Golf Course Maintenance Worker",
      "Athletic Field Maintenance Technician",
    ],
  },
  {
    slug: "roadwork-paving-concrete-heavy-equipment",
    name: "Roadwork, Paving, Concrete & Heavy Equipment",
    description: "Road, site, utility, grading, asphalt, concrete, traffic-control, and earthmoving work.",
    resumeFocus: "Machine type, tonnage or yardage, grade and tolerance, lane or site scope, inspections, production pace, and safe operation.",
    builderTrack: "Roadwork, Paving, Concrete & Heavy Equipment",
    roles: [
      "Asphalt Paver Operator",
      "Asphalt Roller Operator",
      "Paving Laborer",
      "Road Construction Laborer",
      "Heavy Equipment Operator",
      "Excavator Operator",
      "Wheel Loader Operator",
      "Bulldozer Operator",
      "Motor Grader Operator",
      "Skid Steer Operator",
      "Concrete Finisher",
      "Concrete Pump Operator",
      "Traffic Control Flagger",
      "Paving Crew Foreman",
      "Underground Utilities Operator",
      "Trenching and Excavation Operator",
      "Bridge Construction Worker",
    ],
  },
  {
    slug: "roofing-exterior-trades",
    name: "Roofing & Exterior Trades",
    description: "Residential and commercial roofing, sheet metal, waterproofing, siding, gutters, and exterior systems.",
    resumeFocus: "Roof or exterior system, squares or linear feet, tear-off and install scope, equipment, inspections, crew size, and leak-free results.",
    builderTrack: "Roofing & Exterior Trades",
    roles: [
      "Roofer",
      "Commercial Roofer",
      "Residential Roofer",
      "Metal Roofer",
      "Roofing Service Technician",
      "Sheet Metal Roofer",
      "Siding Installer",
      "Gutter Installer",
      "Waterproofing Technician",
      "Building Envelope Technician",
      "Roofing Foreman",
      "Roof Inspector",
    ],
  },
  {
    slug: "automotive-diesel-fleet-maintenance",
    name: "Automotive, Diesel & Fleet Maintenance",
    description: "Cars, trucks, buses, trailers, fleets, heavy equipment, mobile service, and shop operations.",
    resumeFocus: "Vehicle and equipment classes, diagnostics, repair orders, turnaround time, certifications, preventive maintenance, and fleet uptime.",
    builderTrack: "Automotive, Diesel & Fleet Maintenance",
    roles: [
      "Automotive Technician",
      "Diesel Technician",
      "Fleet Maintenance Technician",
      "Heavy Equipment Mechanic",
      "Truck and Trailer Mechanic",
      "Bus Mechanic",
      "Transit Mechanic",
      "Tire and Lube Technician",
      "Brake Technician",
      "Alignment Technician",
      "Mobile Mechanic",
      "Small Engine Mechanic",
      "Shop Foreman",
      "Service Technician",
      "Preventive Maintenance Technician",
    ],
  },
];

export const DETAILED_GUIDE_FAMILIES = TRADE_CAREER_FAMILIES.filter((family) => Boolean(family.guideHref));

export const MAPPED_ROLE_COUNT = new Set(
  TRADE_CAREER_FAMILIES.flatMap((family) => family.roles.map((role) => role.toLocaleLowerCase("en-US"))),
).size;
