import type { Metadata } from "next";
import { PolicyPage, PolicySection, SUPPORT_EMAIL } from "../policy-page";

export const metadata: Metadata = { title: "Privacy Policy", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return (
    <PolicyPage eyebrow="YOUR INFORMATION" title="PRIVACY POLICY" summary="How TRADE HUSTL3 LLC collects, uses, protects, and deletes information across the website, book experience, and Resume Builder.">
      <PolicySection title="1. Who operates this service"><p>TRADE HUSTL3 LLC, located in Atlanta, Georgia, operates tradehustl3.com, the TRADE HUSTL3 Resume Builder, book email list, and related services. Privacy questions may be sent to <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</p></PolicySection>
      <PolicySection title="2. Information we collect"><p>We may collect your name, email address, phone number, city and state, trade interests, employment history, education, skills, tools, licenses, certifications, target job information, support messages, and the information you choose to enter into the Resume Builder. We also collect order identifiers, payment status, refund status, device and browser information, IP-derived security data, and ordinary website analytics.</p><p>Payment-card information is entered directly into Stripe. TRADE HUSTL3 LLC does not receive or store your complete card number.</p></PolicySection>
      <PolicySection title="3. How we use information"><ul><li>Create and secure your account.</li><li>Save your intake and generate, correct, store, and deliver your resume.</li><li>Process purchases, refunds, and protected downloads.</li><li>Send magic links, book samples, purchase delivery, and requested updates.</li><li>Prevent abuse, investigate failures, provide support, and improve the service.</li><li>Meet tax, accounting, dispute, fraud-prevention, and legal obligations.</li></ul></PolicySection>
      <PolicySection title="4. Service providers"><p>We use service providers to operate the business, including Cloudflare for hosting, security, databases, and private file storage; Stripe for payments and refunds; Brevo for transactional and marketing email; Anthropic to assist with resume generation; Google Analytics for website measurement; and GitHub for source-code management. These providers process information under their own terms and privacy practices.</p></PolicySection>
      <PolicySection title="5. AI processing"><p>Resume intake information and correction requests may be sent to Anthropic for the limited purpose of producing the requested resume content. Do not submit Social Security numbers, financial-account information, medical records, passwords, or other information that is unnecessary for a resume.</p></PolicySection>
      <PolicySection title="6. Retention"><p>Resume files and associated generation data may be retained during the seven-day correction period and for up to 30 additional days for service recovery and support. Inactive account information may be deleted or anonymized after two years. Transaction, refund, fraud-prevention, tax, and accounting records may be retained for up to seven years or longer when required by law.</p></PolicySection>
      <PolicySection title="7. Sharing"><p>We do not sell personal information. We may share information with the service providers described above, when you direct us to do so, to protect the service and its users, in connection with a business transfer, or when legally required.</p></PolicySection>
      <PolicySection title="8. Security"><p>We use access controls, private file storage, signed payment notifications, secure cookies, rate limits, and other safeguards appropriate to the service. No online service can guarantee absolute security.</p></PolicySection>
      <PolicySection title="9. Your choices"><p>You may unsubscribe from marketing emails using the link in an email. You may request access, correction, or deletion by emailing <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> from the email connected to your account. We may verify your identity before acting.</p></PolicySection>
      <PolicySection title="10. Age requirement"><p>The Resume Builder and paid digital products are intended for people who are at least 18 years old. We do not knowingly collect personal information from children under 13.</p></PolicySection>
      <PolicySection title="11. Changes"><p>We may update this policy as the service changes. The current version and its effective date will remain posted on this page.</p></PolicySection>
    </PolicyPage>
  );
}
